# Part 1

The file "Purchase_Data.csv" contains purchase data at a Chinese supermarket for various products.  Read this csv into a dataframe called df_data and use the head() method to check that you have read in the data correctly. Make sure you import pandas.

In [31]:
#Write your code here
import pandas as pd

df=pd.read_csv("Data/Purchase_Data.csv")
df.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0

Use the dtypes attribute to view how each column is stored

In [32]:
#Write your code here
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5382 entries, 0 to 5381
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_number  5382 non-null   float64
 1   invoice_time    5382 non-null   str
 2   store_id        5382 non-null   str
 3   product_id      5382 non-null   int64
 4   category_id     5382 non-null   int64
 5   num_item        5382 non-null   float64
 6   price           5382 non-null   float64
dtypes: float64(3), int64(2), str(2)
memory usage: 294.5 KB

Slice the first two columns using .loc and store the result in a variable called result_1.

In [33]:
#Write you code here
#using loc
result_1 = df.loc[:, df.columns[:2]]
print(result_1)

#using iloc
# result_1 = df.iloc[:, :2]
# print(result_1)

      invoice_number   invoice_time
0       2.020000e+11  7/15/15 10:45
1       2.020000e+11  7/15/15 12:16
2       2.020000e+11  7/15/15 12:16
3       2.020000e+11  7/15/15 12:16
4       2.020000e+11  7/15/15 12:16
...              ...            ...
5377    2.020000e+11   9/5/15 23:07
5378    2.020000e+11   9/5/15 23:23
5379    2.020000e+11   9/5/15 23:24
5380    2.020000e+11   9/5/15 23:32
5381    2.020000e+11   9/5/15 23:38

[5382 rows x 2 columns]

Slice the first two rows using .loc and store the result in a variable called result_2.

In [34]:
#Write you code here
result_2 = df.loc[:1]
print(result_2)

   invoice_number   invoice_time store_id  product_id  category_id  num_item  \
0    2.020000e+11  7/15/15 10:45     G816     7000300       210101       1.0
1    2.020000e+11  7/15/15 12:16     G816     7070884        70203       1.0

   price
0    2.0
1    2.0

Slice the first four rows and the first five columns and store the result in a variable called result_3.

In [35]:
#Write your code here
result_3=df.loc[:3 ,df.columns[:5]]
print(result_3)

# result_3=df.iloc[:4 ,:5]
# print(result_3)

   invoice_number   invoice_time store_id  product_id  category_id
0    2.020000e+11  7/15/15 10:45     G816     7000300       210101
1    2.020000e+11  7/15/15 12:16     G816     7070884        70203
2    2.020000e+11  7/15/15 12:16     G816     7070884        70203
3    2.020000e+11  7/15/15 12:16     G816     7070891        70401

Slice rows 0,4,6 and columns invoice time and price and store the result in variable called result_4.

In [36]:
#Write your code here
result_4=df.loc[[0,4,6] ,['invoice_time' , 'price']]
print(result_4)

# i use ai in [2 4 6] as i think that we only use 0:6:2

    invoice_time  price
0  7/15/15 10:45    2.0
4  7/15/15 12:16    6.0
6  7/15/15 15:28    2.0

Store the number rows in a variable called num_rows.

In [37]:

num_rows=df.shape[0]
print(num_rows)

# i dont remember this function so i use ai

5382

Print out the last row of the data to dataframe. **Hint:** use the variable num_rows from the previous exercise.

In [38]:
#Write your code here
last_row=df.loc[num_rows-1]
print(last_row)

invoice_number    202000000000.0
invoice_time        9/5/15 23:38
store_id                    G619
product_id              23030206
category_id               210101
num_item                     1.0
price                        2.0
Name: 5381, dtype: object

# Part 2

Compute the average and max price charged.  Store the results in variables called avg_price and max_price

In [39]:
#Write your code here
avg_price=df['price'].mean()
print(avg_price)

max_price=df['price'].max()
print(max_price)

3.1920522110741363
6.01

Compute the average price and average number of items purchased with only a single call to the mean() method. Store these averages in avg_price and avg_num_items.

In [40]:
#Write you code here
avg_price=df['price'].mean()
print(avg_price)

avg_num_item=df['num_item'].mean()
print(avg_num_item)

3.1920522110741363
1.2983091787439613

Create a column called "total", which is the product of the price and num_item columns.

In [41]:
#Write your code here
df['total']=df['price']*df['num_item']
df.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price,total
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0,6.0

What is the avgerage price of the three most expensive purchases?

In [42]:
#Write your code here
avg_top_3 = df["price"].nlargest(3).mean()
print(avg_top_3)

# i dont know .nlargest so i use ai

6.003333333333333

How many different products are there?

In [43]:
#Write your code here
num_products = df["product_id"].nunique()
print(num_products)

53

Find the difference between the mean and median of the column total.  Use the describe() method and then index the dataframe it returns.

In [44]:
#Write your code here
# df.describe()
mean= df['total'].describe()['mean']
median= df['total'].describe()['50%']

diff=mean-median
print(diff)

0.9318078781127839

Use the drop() method to delete the column total from the dataframe df_data.

In [45]:
#Write your code here
df=df.drop('total' ,axis=1)
df.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0

Let's dig a little deeper into the data set and answer some basic question.

In [46]:
#Write your code here

First, covert the column invoice time to a datetime column. Print out the new column types to make sure this was done correctly

In [47]:
#Write your code here
df["invoice_time"] = pd.to_datetime(df["invoice_time"])
print(df.dtypes)

invoice_number           float64
invoice_time      datetime64[us]
store_id                     str
product_id                 int64
category_id                int64
num_item                 float64
price                    float64
dtype: object

C:\Users\asus\AppData\Local\Temp\ipykernel_13628\496183982.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["invoice_time"] = pd.to_datetime(df["invoice_time"])

Next, let's create columns called "DOW" and "Month", which store the corresponding weekday and month of the invoice respectively.  Print the head of the dataframe to make sure this was done correctly.

In [48]:
#Write your code here
df["DOW"] = df["invoice_time"].dt.day_name()
df["Month"] = df["invoice_time"].dt.month

print(df.head())

#i dont know this function so i use ai

   invoice_number        invoice_time store_id  product_id  category_id  \
0    2.020000e+11 2015-07-15 10:45:00     G816     7000300       210101
1    2.020000e+11 2015-07-15 12:16:00     G816     7070884        70203
2    2.020000e+11 2015-07-15 12:16:00     G816     7070884        70203
3    2.020000e+11 2015-07-15 12:16:00     G816     7070891        70401
4    2.020000e+11 2015-07-15 12:16:00     G816     7090363        70401

   num_item  price        DOW  Month
0       1.0    2.0  Wednesday      7
1       1.0    2.0  Wednesday      7
2       1.0    2.0  Wednesday      7
3       1.0    6.0  Wednesday      7
4       1.0    6.0  Wednesday      7

Create a variable called num_purchases_wed, which stores the number of purchases made on Wednesday?  You should use value_counts and then index the series it return.

In [49]:
#Write your code here
num_purchases_wed = df["DOW"].value_counts()["Wednesday"]

print(num_purchases_wed)

959

# Part 3

In this set of practice exercises, we will be working with a demographic data regarding the passengers aboard the Titanic.  Read in the data frame and use the head() method to check that it was read in correctly.

In [50]:
#Write your code here
df=pd.read_csv("Data/Titanic.csv")
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Use the rename method to change the column "Name" to "Passenger_Name" and the column "Ticket" to "Ticket_Num".

In [51]:
#Write your code here
df=df.rename(columns={'Name' : 'Passenger_Name' ,'Ticket' : 'Ticket_Num'})
df.head()

,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Change the index of the df_titanic to the column PasengerID.

In [52]:
#Write your code here
df.set_index("PassengerId" , inplace= True)
df.head()

,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,
892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Select the name of passenger 896

In [53]:
#Write your code here
passenger_896_name = df.loc[896, "Passenger_Name"]
print(passenger_896_name)

Hirvonen, Mrs. Alexander (Helga E Lindqvist)

Change the index back to row numbers but making sure that we don't lose the PassengerId column.

In [54]:
#Write your code here
# df.reset_index(inplace= True)
# df.head()

How many missing entries are there in the Age column? Use the isnull() method and recall than Booleans are exactly like 1s (True) and 0s (False).

In [55]:
#Write you code here
df["Age"].isnull().count()

np.int64(418)

Compute the avg age of passengers ignoring the missing data.

In [56]:
#Write your code here
df["Age"].mean()

np.float64(30.272590361445783)

Using the fillna() method replace the missing values in the Age column with the mean.

In [57]:
#Write your code here
df["Age"].fillna(df["Age"].mean())

PassengerId
892     34.50000
893     47.00000
894     62.00000
895     27.00000
896     22.00000
          ...
1305    30.27259
1306    39.00000
1307    38.50000
1308    30.27259
1309    30.27259
Name: Age, Length: 418, dtype: float64

What is the average age of the 5 oldest passengers? The reset_index method will be helpful here.

In [58]:
#Write your code here
df['Age'].nlargest(5).mean()

np.float64(67.0)